name: main

on:
  # schedule:
  #   - cron: "0 15 * * *" # runs every day at 3pm
  push

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
    
    steps:
      # - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8' 
          architecture: 'x64' 
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: Checkout predictit-bot
        uses: actions/checkout@v2
        with:
          path: predictit-bot
      - name: Checkout dbdotcom
        uses: actions/checkout@v2
        with:
          repository: dalton-b/dbdotcom
          path: dbdotcom
      - name: Update data
        run: |
          cd predictit-bot
          bash run.sh
      - name: Commit to predictit-bot
        run: |
          cd predictit-bot
          git config --local user.name "dalton-b"
          git commit -m "Daily update" -a
      - name: Push changes to preditcit-bot
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
          directory: predictit-bot
      - name: Copy to dbdotcom
        run: |
          cp predictit-bot/predictit-forecasting.html dbdotcom
          cd dbdotcom
          git config --local user.name "dalton-b"
          git add .
          git commit -m "Daily update" -a
      # - name: Check 
      #   run: |
      #     cd dbdotcom
      #     git fetch
      #     git pull
      - name: Push changes to dbdotcom
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
          force: true
          directory: dbdotcom


